#!/usr/bin/env python3
"""
Prepare medical-domain SFT training data for the Router model.

Source: core/datasets/biomedical/sessions.jsonl  (generated by 1_convert_to_sessions.py)

Strategy:
  - complete  (cat=0) QA  → optimal_action = "R"  (completeness; summaries may omit entities)
  - first_visit (cat=1) QA → optimal_action = "R"  (temporal precision; summary collapses visits)
  - latest     (cat=2) QA  → optimal_action = "S"  (recent info is likely in the newest summary)

Synthetic summaries simulate what a real med-memgate run would retrieve:
  - For R-path samples: only the LATEST visit's doctor text is "retrieved" (incomplete for complete/first queries)
  - For S-path samples: the latest visit's doctor text is complete enough for the latest-entity query

Output format matches 2_prepare_sft_data_v2.py exactly:
  {"messages": [{"role": "user", ...}, {"role": "assistant", ...}], "metadata": {...}}

Usage:
    python scripts/router_training/4_prepare_medical_sft_data.py \
        --sessions core/datasets/biomedical/sessions.jsonl \
        --output   data/router_sft_medical/train.jsonl \
        [--merge   data/router_sft_v2/train.jsonl]
"""

import argparse
import json
import random
from pathlib import Path
from typing import Any, Dict, List, Optional


# ── Router prompt (mirrors 2_prepare_sft_data_v2.py) ──────────────────────────

ROUTER_PROMPT_V2 = """You are an expert router for a memory-augmented QA system.

Your task: Analyze the retrieved summaries and decide the best action to answer the question.

Available actions:
1. "S" - Answer using current summaries only
    Use when: Summaries contain the EXPLICIT answer to the specific question.
    CRITICAL: Do not infer causes from effects (e.g., "benefits of X" is NOT "reason for starting X").
    If the exact answer is not verbatim in the text, or the question needs efficient details do not use S.

2. "R" - Deep research mode (slow path)
    Use when: Summaries are ambiguous.
    If the question requires completeness (e.g., "how many times", "list all", "what are all", "Both of them"), prefer R to ensure comprehensive answers.


Question: {question}

Retrieved Summaries:
{summaries_block}

Output format (JSON only):
- If answering with summaries: {{"action": "S"}}
- If deep research needed: {{"action": "R"}}

Your response:"""


# ── Synthetic summary generation ───────────────────────────────────────────────

def _build_synthetic_summaries(session: Dict[str, Any], optimal_action: str) -> List[str]:
    """
    Build plausible retrieved summaries for the router prompt.

    For R samples: only the last visit's doctor text is returned (simulating a
    summary index that captured the most recent visit but not earlier ones).

    For S samples: the last visit's doctor text is returned as a complete entry
    (sufficient to answer the "latest" query).
    """
    turns = session.get("turns", [])
    # Collect doctor turns grouped by visit (dia_id is 1, 3, 5, … for doctors)
    doctor_turns = [t for t in turns if t.get("speaker", "").lower() == "doctor"]

    if not doctor_turns:
        return ["(no summaries)"]

    if optimal_action == "S":
        # Return the most recent doctor turn as a well-scored summary
        latest = doctor_turns[-1]
        return [f"[Scene: Medical Consultation] {latest['text']}"]
    else:
        # Return only the last doctor turn (missing earlier visit entities → R needed)
        latest = doctor_turns[-1]
        partial = f"[Scene: Medical Consultation] {latest['text']}"
        # Add a low-score filler to simulate incomplete retrieval
        filler = "[Scene: Patient Background] Patient has been attending regular follow-up consultations."
        return [partial, filler]


# ── SFT sample construction ────────────────────────────────────────────────────

def build_sft_sample(
    session: Dict[str, Any],
    qa: Dict[str, Any],
    optimal_action: str,
) -> Dict[str, Any]:
    summaries = _build_synthetic_summaries(session, optimal_action)
    scores = [0.85 if i == 0 else 0.45 for i in range(len(summaries))]

    summaries_lines = [
        f"[{i}] score={scores[i]:.3f}\n{s}"
        for i, s in enumerate(summaries)
    ]
    summaries_block = "\n\n".join(summaries_lines)

    user_prompt = ROUTER_PROMPT_V2.format(
        question=qa["question"],
        summaries_block=summaries_block,
    )

    # Build chain-of-thought thinking
    qa_type = qa.get("meta", {}).get("qa_type", "complete")
    if optimal_action == "R":
        if qa_type == "complete":
            thinking = (
                "The question asks for all entities mentioned across all visits. "
                "The retrieved summary only captures the most recent visit, so it likely misses "
                "entities from earlier consultations. Completeness cannot be guaranteed from summaries alone. "
                "Deep research is needed to scan the full conversation history."
            )
        else:  # first_visit
            thinking = (
                "The question asks about the first visit specifically. "
                "The retrieved summary reflects the latest consultation, not the initial visit. "
                "Temporal precision requires accessing the original raw records. "
                "Deep research is needed."
            )
    else:  # S
        thinking = (
            "The question asks about the most recently mentioned information. "
            "The retrieved summary captures the latest consultation, which directly contains the answer. "
            "No need to search further — the summary is sufficient."
        )

    if optimal_action == "R":
        thinking += " Therefore, deep research mode is needed."
    else:
        thinking += " Therefore, I'll answer using the summaries directly."

    assistant_response = f"<think>\n{thinking}\n</think>\n\n{{\"action\": \"{optimal_action}\"}}"

    return {
        "messages": [
            {"role": "user", "content": user_prompt},
            {"role": "assistant", "content": assistant_response},
        ],
        "metadata": {
            "query_id": qa["query_id"],
            "session_id": session["session_id"],
            "action": optimal_action,
            "qa_type": qa_type,
            "domain": "biomedical",
        },
    }


# ── Main ───────────────────────────────────────────────────────────────────────

def load_sessions(path: Path) -> List[Dict[str, Any]]:
    sessions = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                sessions.append(json.loads(line))
    return sessions


def main():
    parser = argparse.ArgumentParser(description="Prepare medical SFT data for Router")
    parser.add_argument("--sessions", default="core/datasets/biomedical/sessions.jsonl",
                        help="Path to biomedical sessions.jsonl")
    parser.add_argument("--output", default="data/router_sft_medical/train.jsonl",
                        help="Output path for SFT samples")
    parser.add_argument("--merge", default=None,
                        help="If given, append samples to this existing .jsonl file")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    random.seed(args.seed)

    sessions_path = Path(args.sessions)
    if not sessions_path.exists():
        print(f"ERROR: {sessions_path} not found. Run 1_convert_to_sessions.py first.")
        return

    sessions = load_sessions(sessions_path)

    sft_samples: List[Dict[str, Any]] = []
    counts = {"R": 0, "S": 0}

    for session in sessions:
        for qa in session.get("qa_pairs", []):
            optimal_action = qa.get("meta", {}).get("optimal_route", "R")
            if optimal_action not in ("S", "R"):
                optimal_action = "R"
            sample = build_sft_sample(session, qa, optimal_action)
            sft_samples.append(sample)
            counts[optimal_action] += 1

    random.shuffle(sft_samples)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if args.merge and Path(args.merge).exists():
        # Append to existing file
        with open(Path(args.merge), "a", encoding="utf-8") as f:
            for s in sft_samples:
                f.write(json.dumps(s, ensure_ascii=False) + "\n")
        print(f"Appended {len(sft_samples)} samples to {args.merge}")
    else:
        with open(output_path, "w", encoding="utf-8") as f:
            for s in sft_samples:
                f.write(json.dumps(s, ensure_ascii=False) + "\n")
        print(f"Wrote {len(sft_samples)} samples to {output_path}")

    print(f"  R samples : {counts['R']}")
    print(f"  S samples : {counts['S']}")
    print(f"  R ratio   : {counts['R'] / max(len(sft_samples), 1):.1%}")


if __name__ == "__main__":
    main()
